apiVersion: v1
kind: ServiceAccount
metadata:
  name: booster-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: booster-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: booster-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: booster-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
        cacheSumSize: "2Gi"
        netWeiht: "1.5"
        layerWeight: "2"
    spec:
      serviceAccountName: booster-scheduler
      containers:
      - image: fengyicheng/fengscheduler:v2
        name: booster-scheduler
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/hostname: master70