apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
        limit_bandwidth: '1'
        limit_delay: '250'
      name: pod1
    spec:
      containers:
      - image: httpd:2.4.43
        imagePullPolicy: Never
        name: httpd
        resources:
          limits:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 1Gi
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 1Gi
      schedulerName: booster-scheduler
